issues:
  exclude-rules:
    - source: "(noinspection|TODO)"
      linters: [ godot ]
    - source: "//noinspection"
      linters: [ gocritic ]
    - path: "_test\\.go"
      linters:
        - bodyclose
        - dupl
        - funlen
        - goconst
        - gosec
        - noctx
        - wrapcheck
    - linters: [ staticcheck ]
      text: "options.AndFrom is deprecated"
    - linters: [ staticcheck ]
      text: "The component config package has been deprecated and will be removed in a future release."
    - path: "cmd/"
      linters:
        - gochecknoinits
        - gochecknoglobals
    # Exclude `lll` issues for long lines with `go:generate`.
    - linters:
        - lll
      source: '^//\s*\+kubebuilder:'
    - linters:
        - godot
      source: '^//\s*\+optional'
    - path: "api/v1/"
      linters:
        - gochecknoinits
    # Allow dot imports for ginkgo and gomega
    - source: ginkgo|gomega
      linters:
        - revive
      text: "should not use dot imports"
    - path: "."
      linters:
        - gochecknoglobals
